### PR TITLE
Create fix for paths that contain spaces

### PR DESCRIPTION
**Pull request by meinaart**
Paths that contain spaces caused grunt-scss-lint to incorrectly report that all files are lint free.

This commit/pull request fixes that.

Also:
- Added tests for spaces in paths
- Made tests more sturdy
- Made tests compatible with latest version of scss-lint
- Incremented version number from 0.3.8 to 0.3.9
- Fixed license field in `package.json` according to [specs](https://docs.npmjs.com/files/package.json#license)
- Added myself as contributor ;)

### CODE REVIEW

**Comment by ahmednuaman** [comment]
Any news on this?

**Comment by meinaart** [comment]
@ahmednuaman: can you merge it?

**Comment by ahmednuaman** [comment]
Only when the tests pass.

**Comment by ahmednuaman** [comment]
What's happening with this?

**Comment by meinaart** [comment]
@ahmednuaman Updated my branch with master and fixed the tests (so they should also work on paths with spaces).

**Comment by meinaart** [comment]
Tests are still failing, looking into that.

**Comment by meinaart** [comment]
appveyor seems to be failing on the colourize output stuff. I think this has to do with the fact it runs under Windows. Should I worry about that?

**Comment by ahmednuaman** [comment]
What's the news on this?

**Pull request closed without merging**
