### PR TITLE
Added Json format

### PR DESCRIPTION
**Pull request by DBaker85**
Added the reporter option that allows to choose between xml and JSON.
Added extension checks to add proper extensions to files
Added global wrapper to JSON output for use when concatenating files

### CODE REVIEW

**Comment by ahmednuaman** [comment]
Thanks, do you mind fixing the errors first?

**Comment by DBaker85** [comment]
Yeah sorry.

A little new to pull requests.

**Comment by DBaker85** [comment]
If I understood your tests correctly. It seems to be fine now.

**Comment by ahmednuaman** [comment]
:(

**Comment by ahmednuaman** [comment]
Any news?

**Comment by DBaker85** [comment]
Well, the change works, but the tests are failing because of a timeout on various tests. It seems to be random on each build. I get this error: 
```1) grunt-scss-lint exit code on failure:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.```

**Comment by ahmednuaman** [comment]
Any news on this?

**Pull request closed without merging**
