### PR TITLE
Adds option to fail or not fail on lint warning

### PR DESCRIPTION
**Pull request by nick11703**
This allows the option to not fail the task if only lint warnings are received. This should also help with issue #133. You can provide a severity level within the SCSS Lint configuration file for each individual linter or a global overall severity. https://github.com/brigade/scss-lint#severities & https://github.com/brigade/scss-lint/blob/master/config/default.yml

If this is approved and merged, Can you create a new NPM package? Thanks.

### CODE REVIEW

**Comment by nick11703** [comment]
I didn't realize there were conflicts in this PR. Should be good to go now. I also noticed that the tests would always pass if compact mode was enabled. The regex was in the compact.make method was not making any matches. https://github.com/ahmednuaman/grunt-scss-lint/blob/master/tasks/lib/scss-lint.js#L68 Looks like there was another colon and number appended to the file name that the regex was not looking for.

**Comment by ahmednuaman** [comment]
Yo, sorry for the delay, checking now.

**Comment by ahmednuaman** [comment]
Tests be failing, any reason why?

**Comment by nick11703** [comment]
@ahmednuaman Can you provide the error?

**Comment by ahmednuaman** [comment]
I can't seem to find the travis test, this is a bit crazy, can you run `npm t` locally?

**Comment by nick11703** [comment]
I get a `Warning: Task "mocha_istanbul:tests" failed. Use --force to continue.` Not sure why.

**Comment by nick11703** [comment]
@ahmednuaman I got the errors fixed. I had to update to return the results as well as the status. Can you please review again. Thanks.

**Comment by nick11703** [comment]
@ahmednuaman Thanks for merging.

**Pull request merged**
