### PR TITLE
Adding output of number of files inspected in case of failing

### PR DESCRIPTION
**Pull request by barzik**
I've needed output of the number of files linted, so I've added fileReport option. if someone is setting it to true, The report will include the numbers of files that were inspected. I've also added test spec for this.

### CODE REVIEW

**Comment by ahmednuaman** [comment]
Care to fix please?

**Comment by barzik** [comment]
The build is broken by Lint errors (not created by my code). Do you prefer me to insert the fixes in this pull request or to create another pull request?

**Comment by ahmednuaman** [comment]
It looks like they are your code errors. I can only merge this PR when the builds are passing.

**Comment by barzik** [comment]
You are very right about the lint issues (sorry about that!). But please look on the Travis CI failed. it failed because of time out issues for other test. Can you provide input for handling it?

**Comment by ahmednuaman** [comment]
Not sure, haven't seen that before. Did you sort your hinting out?

**Comment by barzik** [comment]
It seems that some of tests are experienced time out issues. it is not relevant to the code itself. you can see that the build failed in this pull request, although the file that was changed is only readme file:
https://github.com/ahmednuaman/grunt-scss-lint/pull/120

I have trouble to reproduce it in my main dev machine, but I have slower machine that it happens their as well. temporary solution will be pushing up the timeout level. But We need to take a closer look on the tests.

**Comment by ahmednuaman** [comment]
Any news on this?

**Pull request closed without merging**
