### PR TITLE
Change gem name from scss-lint to scss_lint in README.md

### PR DESCRIPTION
**Pull request by chrisnicotera**
Although the project is still named scss-lint, the Gem is now named `scss_lint`.

I assume scss-lint is left in place for legacy purposes, as it seems to have changed ownership from [causes](https://github.com/causes) to [brigade](https://github.com/brigade). The last release of `scss-lint` (causes) is 0.38.0, from May 3, 2015.

### CODE REVIEW

**Comment by ahmednuaman** [comment]
What about the gemfile too?

**Comment by rek** [comment]
Gem file is updated, it is confusing to not have the readme updated too.

+1

**Comment by alexcanessa** [comment]
@ahmednuaman could I suggest to merge this PR sooner than later?

**Comment by ahmednuaman** [comment]
Why are the tests failing?

**Comment by chrisnicotera** [comment]
@ahmednuaman https://travis-ci.org/ahmednuaman/grunt-scss-lint/jobs/80890455#L317-L324

The test didn't finish in time. This is [also happening on Appveyor](https://ci.appveyor.com/project/ahmednuaman/grunt-scss-lint/build/1.0.29/job/0kib7o0w22uf2jv7#L487) although with a [couple](https://ci.appveyor.com/project/ahmednuaman/grunt-scss-lint/build/1.0.29/job/0kib7o0w22uf2jv7#L491) [of other](https://ci.appveyor.com/project/ahmednuaman/grunt-scss-lint/build/1.0.29/job/0kib7o0w22uf2jv7#L501], unrelated errors.

Perhaps consider increasing the mocha test timeout since these tests are spawning grunt and most of them are approaching the 2000ms default?

I've only modified `README.md`, so the tests failing for this PR is moot, but that should resolve the issue that both CI suites are experiencing.

**Comment by ahmednuaman** [comment]
Try to rebase and try again

**Comment by chrisnicotera** [comment]
@ahmednuaman Should be good to go

**Pull request merged**
